"""Add leaderboard model

Revision ID: 536a253b4c22
Revises: 9061564cff44
Create Date: 2026-04-18 12:53:53.243905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536a253b4c22'
down_revision = '9061564cff44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('total_lessons_completed', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('highest_streak', sa.Integer(), nullable=True),
    sa.Column('total_practice_score', sa.Integer(), nullable=True),
    sa.Column('average_accuracy', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_spent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accuracy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('session_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_attempt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_column('last_attempt')
        batch_op.drop_column('session_count')
        batch_op.drop_column('accuracy')
        batch_op.drop_column('time_spent')
        batch_op.drop_column('attempts')
        batch_op.drop_column('best_score')

    op.drop_table('leaderboard')
    # ### end Alembic commands ###
