name: Deploy Backend to Ubuntu Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 103.249.201.193
          username: root
          password: PLaa6jtq
          port: 22
          source: "source/backend/*"
          target: "/var/www/AMPV2"
          strip_components: 0

      - name: Restart Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 103.249.201.193
          username: root
          password: PLaa6jtq
          port: 22
          script: |
            # Môi trường đã được setup Node.js v20 và PM2 trên server
            cd /var/www/AMPV2/source/backend
            npm install
            npx prisma generate
            pm2 restart backend-api || pm2 start server.js --name backend-api
